import { library } from '@fortawesome/fontawesome-svg-core';
import {
	faUser,
	faMap,
	faHouse,
	faCog,
	faSignOut,
	faTrash,
	faPlus,
	faMinus,
	faCheck,
	faTimes,
	faSpinner,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faChevronDown,
	faBars,
	faCircle,
	faSquare,
	faHeart,
	faStar,
	faLocationDot,
	faSwords,
	faBell,
	faCheckCircle,
	faExclamationTriangle,
	faInfoCircle,
} from '@fortawesome/pro-solid-svg-icons';

import {
	faUser as faUserRegular,
	faHeart as faHeartRegular,
	faStar as faStarRegular,
} from '@fortawesome/pro-regular-svg-icons';

import {
	faUser as faUserLight,
} from '@fortawesome/pro-light-svg-icons';

library.add(
	faUser,
	faMap,
	faHouse,
	faCog,
	faSignOut,
	faTrash,
	faPlus,
	faMinus,
	faCheck,
	faTimes,
	faSpinner,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faChevronDown,
	faBars,
	faCircle,
	faSquare,
	faHeart,
	faStar,
	faLocationDot,
	faSwords,
	faBell,
	faCheckCircle,
	faExclamationTriangle,
	faInfoCircle,
	faUserRegular,
	faHeartRegular,
	faStarRegular,
	faUserLight,
);
